-- Create the members table
CREATE TABLE IF NOT EXISTS members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname text NOT NULL,
  lastname text NOT NULL,
  imageurl text,
  role text DEFAULT 'Member',
  sociallinks jsonb,
  priority integer,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public access (since we are using the anon key)
-- Policy for SELECT (Read)
CREATE POLICY "Enable read access for all users" ON members
    FOR SELECT
    USING (true);

-- Policy for INSERT (Create)
CREATE POLICY "Enable insert for all users" ON members
    FOR INSERT
    WITH CHECK (true);

-- Policy for UPDATE (Update)
CREATE POLICY "Enable update for all users" ON members
    FOR UPDATE
    USING (true);

-- Policy for DELETE (Delete)
CREATE POLICY "Enable delete for all users" ON members
    FOR DELETE
    USING (true);
